# Generated by Django 5.2.7 on 2025-11-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_booking_options_alter_booking_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('full', 'Pay in Full'), ('installment', 'Pay in Two Installments')], max_length=20)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deposit_deadline', models.DateField()),
                ('final_payment_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic Tier - Meeting Basic Needs'), ('standard', 'Standard Tier - Regular Income'), ('solidarity', 'Solidarity Tier - Financially Secure')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sessions', models.IntegerField(default=5)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='courses.course')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('course', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Payment Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('final_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='courses.booking')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.paymentplan')),
                ('pricing_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.pricingtier')),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit Payment'), ('full', 'Full Payment'), ('final', 'Final Payment')], max_length=10)),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('course_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to='courses.coursepayment')),
            ],
        ),
    ]
