# Generated by Django 5.2.7 on 2025-11-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_paymentplan_pricingtier_coursepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursepayment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
