# Generated by Django 5.2.7 on 2025-11-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursepayment_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courses.course'),
        ),
    ]
