# Generated by Django 4.2.7 on 2025-11-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_booking_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Session number (e.g., 1, 2, 3)')),
                ('date', models.DateField(help_text='Date of this session')),
                ('start_time', models.TimeField(help_text='Start time of this session')),
                ('end_time', models.TimeField(help_text='End time of this session')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
            options={
                'ordering': ['session_number'],
                'unique_together': {('course', 'session_number')},
            },
        ),
    ]
