# Generated by Django 4.2.7 on 2025-11-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='accessibility',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_structure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_you_will_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_you_will_gain',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='who_this_is_for',
            field=models.TextField(blank=True),
        ),
    ]
