# Generated by Django 5.2.7 on 2025-11-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_accessibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_notification_emails', models.TextField(default='hannah@hortuscognitor.co.uk', help_text='Email addresses to notify when a booking is made. Separate multiple emails with commas.', verbose_name='Booking Notification Emails')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
