# Generated by Django 5.2.7 on 2025-11-17 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='course_details_days_before',
            field=models.IntegerField(default=7, help_text='How many days before course start date to send the course details email.', verbose_name='Course Details Days Before'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='course_details_enabled',
            field=models.BooleanField(default=True, help_text='Send course details and preparation information to confirmed participants before the course starts.', verbose_name='Enable Course Details Reminders'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_reminder_days_before_list',
            field=models.CharField(default='7,3,1', help_text='Comma-separated list of days before final payment deadline to send reminders. For example: "7,3,1" sends reminders 7 days before, 3 days before, and 1 day before the deadline.', max_length=100, verbose_name='Payment Reminder Days Before'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Send automated payment reminders to customers who paid a deposit and need to pay the final amount.', verbose_name='Enable Payment Reminders'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reminder_test_email',
            field=models.EmailField(blank=True, default='hannah@hortuscognitor.co.uk', help_text='Email address to receive all reminder emails when test mode is enabled.', max_length=254, verbose_name='Test Email Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reminder_test_mode',
            field=models.BooleanField(default=False, help_text='When enabled, all automated reminder emails will be sent to the test email address instead of actual recipients. Use this to test the system before going live.', verbose_name='Enable Test Mode'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_reminder_days_before',
            field=models.IntegerField(default=1, help_text='How many days before each session to send the reminder.', verbose_name='Session Reminder Days Before'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Send reminders before individual course sessions.', verbose_name='Enable Session Reminders'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_reminder_per_course',
            field=models.CharField(choices=[('first_only', 'First Session Only'), ('all_sessions', 'All Sessions')], default='first_only', help_text='Send reminders only for the first session or for all sessions.', max_length=20, verbose_name='Session Reminder Frequency'),
        ),
        migrations.CreateModel(
            name='EmailReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('payment_reminder', 'Payment Reminder'), ('course_details', 'Course Details'), ('session_reminder', 'Session Reminder')], help_text='Type of reminder email sent', max_length=20)),
                ('days_before_sent', models.IntegerField(blank=True, help_text='How many days before the event this reminder was sent (e.g., 7 for "7 days before")', null=True)),
                ('recipient_email', models.EmailField(help_text='Email address the reminder was sent to', max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the reminder was sent')),
                ('successful', models.BooleanField(default=True, help_text='Whether the email was sent successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if email failed to send')),
                ('course_payment', models.ForeignKey(blank=True, help_text='Related course payment (for payment reminders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='courses.coursepayment')),
                ('course_session', models.ForeignKey(blank=True, help_text='Related course session (for session reminders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='courses.coursesession')),
            ],
            options={
                'verbose_name': 'Email Reminder',
                'verbose_name_plural': 'Email Reminders',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['reminder_type', 'sent_at'], name='courses_ema_reminde_f8c2a0_idx'), models.Index(fields=['course_payment', 'reminder_type', 'days_before_sent'], name='courses_ema_course__b73a99_idx'), models.Index(fields=['course_session', 'reminder_type'], name='courses_ema_course__366e4d_idx')],
            },
        ),
    ]
