# Generated by Django 5.2.7 on 2025-11-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_sitesettings_course_details_days_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text="Booking status - set to 'confirmed' once payment received, 'cancelled' to stop reminders", max_length=20),
        ),
    ]
